name: Ejecutar bot cada 3 minutos

on:
  schedule:
    - cron: "*/1 * * * *"
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install notion-client schedule

      - name: Ejecutar el bot
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          DATABASE_ORIGEN_ID: ${{ secrets.DATABASE_ORIGEN_ID }}
          DATABASE_DESTINO_ID: ${{ secrets.DATABASE_DESTINO_ID }}
        run: python bot.py
